Support portal subdomain and context path deployment
medizininformatik-initiative/feasibility-deploy pull request #92
Opened 2024-07-22 07:40 UTC by DeaDurro

2024-07-23 12:02 UTC, DeaDurro commented
is it a problem if the backend path is /api when then "api": {
    "baseUrl": "/api" in the deploy-config.json.default?

2024-08-05 15:27 UTC, EmteZogaf requested changes
The 3 commits need actual [commit messages](https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53) and can probably be squashed into 1 commit.

2024-08-05 15:27 UTC, EmteZogaf commented on feasibility-portal/proxy/docker-compose.yml
> +      - ${PROXY_NGINX_CONFIG_PATH:-./context-paths.nginx.conf}:/etc/nginx/nginx.conf:ro
Please remove whitespaces at the end of line.

2024-08-05 15:27 UTC, EmteZogaf commented on feasibility-portal/README.md
> +
Reduce empty lines to 1 or maybe 2.

2024-08-19 10:47 UTC, EmteZogaf approved these changes

2024-09-04 12:54 UTC, merged